const colors = {
  light: {
    text: "#0d1a3a",
    tint: "#1a5e9a",
    background: "#f4f7ff",
    foreground: "#0d1a3a",
    card: "#ffffff",
    cardForeground: "#0d1a3a",
    primary: "#1a5e9a",
    primaryForeground: "#ffffff",
    primaryLight: "#ddeaf8",
    primaryXLight: "#f0f6fd",
    primaryDark: "#0e3d6e",
    secondary: "#ddeaf8",
    secondaryForeground: "#0e3d6e",
    muted: "#f0f6fd",
    mutedForeground: "#6a7a96",
    accent: "#2db56e",
    accentForeground: "#ffffff",
    accentLight: "#d6f5e7",
    accentDark: "#1a7a4a",
    destructive: "#e03e3e",
    destructiveForeground: "#ffffff",
    destructiveLight: "#fde8e8",
    border: "#d5dff0",
    borderLight: "#edf1f9",
    input: "#d5dff0",
    amber: "#e08c1a",
    amberLight: "#fef3dc",
    gold: "#c9860d",
    goldLight: "#fff3db",
    purple: "#7c3aed",
    purpleLight: "#f3effe",
  },
  radius: 14,
};

export default colors;
